name: Release

on:
  push:
    branches:
      - main
      - hotfix**

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_HOME: /.cargo

jobs:
  package-version: # emit package version using `cargo tree -i`
    name: Get Package Version
    runs-on: ubuntu-latest
    container: rust:1.57.0-slim
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.CARGO_HOME }}/bin/
            ${{ env.CARGO_HOME }}/registry/index/
            ${{ env.CARGO_HOME }}/registry/cache/
            ${{ env.CARGO_HOME }}/git/db/
          key: ${{ runner.os }}-cargo-home-${{ hashFiles('**/Cargo.lock') }}
      - name: Get package version
        id: get_version
        working-directory: ./libwasmvm
        run: |
          VERSION=$(cargo tree -i wasmvm | grep -oE "[0-9]+(\.[0-9]+){2}-[0-9]+(\.[0-9]+){2}")
            echo ::set-output name=version::v$VERSION
      - name: Get latest tag
        id: get_latest_tag
        uses: actions-ecosystem/action-get-latest-tag@v1
  push-tag: # if the version does not exist as git tag, push it
    name: Push Tag
    needs:
      - package-version
    if: ${{ needs.package-version.outputs.version != needs.package-version.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Push Tag to GitHub
        run: |
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
          -d "{\"ref\": \"refs/tags/${{ needs.get_version.outputs.version }}\", \"sha\": \"${GITHUB_SHA}\"}" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/git/refs"
